# Generated by Django 4.1.7 on 2023-09-04 13:19

from django.db import migrations
from AulaWeb.models import Usuario
from django.contrib.auth.models import User

def criar_root(apps, schema):
    u = User.objects.create_user(username='root', password='root', email='root@localhost')
    usr = Usuario()
    usr.user = u
    usr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('AulaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_root)
    ]

